<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LogicTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Gomoku\Game\GameCore.cs" Link="Game\GameCore.cs" />
    <Compile Include="..\..\Gomoku\AI\AiEngine.cs" Link="AI\AiEngine.cs" />
  </ItemGroup>

</Project>
